print(type("Hello World"))	
print(type(20))
print(type(20.5))		
print(type(1j))		
print(type(["apple", "banana", "cherry"]))		
print(type(("apple", "banana", "cherry")))		
print(type(range(6)))		
print(type({"name" : "John", "age" : 36}))		
print(type({"apple", "banana", "cherry"}))		
print(type(frozenset({"apple", "banana", "cherry"})))		
print(type(True))	
print(type(b"Hello"))	
print(type(bytearray(5)))		
print(type(memoryview(bytes(5))))


str("Hello World")		
int(20)		
float(20.5)		
complex(1j)		
list(("apple", "banana", "cherry"))		
tuple(("apple", "banana", "cherry"))		
range(6)		
dict(name="John", age=36)		
set(("apple", "banana", "cherry"))		
frozenset(("apple", "banana", "cherry"))		
bool(5)		
bytes(5)		
bytearray(5)	
memoryview(bytes(5))
